allowBuilds:
  esbuild: true
  workerd: true
  wrangler: true
minimumReleaseAgeExclude:
  - eslint@10.12.0
  - eslint-plugin-unicorn@77.0.0
  - eslint-config-narwhal@1.0.2 || 2.0.0 || 2.1.0 || 2.1.1
  - '@typescript-eslint/eslint-plugin@8.71.1'
  - '@typescript-eslint/parser@8.71.1'
  - '@typescript-eslint/project-service@8.71.1'
  - '@typescript-eslint/scope-manager@8.71.1'
  - '@typescript-eslint/tsconfig-utils@8.71.1'
  - '@typescript-eslint/type-utils@8.71.1'
  - '@typescript-eslint/types@8.71.1'
  - '@typescript-eslint/typescript-estree@8.71.1'
  - '@typescript-eslint/utils@8.71.1'
  - '@typescript-eslint/visitor-keys@8.71.1'
  - typescript-eslint@8.71.1
