import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cssPath = join(root, 'src/shared.css');
const outPath = join(root, 'src/css.ts');
const checkOnly = process.argv.includes('--check');

const css = readFileSync(cssPath, 'utf8').trim();
const source = `/** Generated by scripts/embed-css.mjs — edit src/shared.css instead. */
export const SHARED_CSS = ${JSON.stringify(css)};
`;

if (checkOnly) {
  let current;
  try {
    current = readFileSync(outPath, 'utf8');
  } catch {
    console.error('src/css.ts is missing. Run: pnpm run embed-css');
    process.exit(1);
  }
  if (current !== source) {
    console.error(
      'src/css.ts is out of date with src/shared.css. Run: pnpm run embed-css',
    );
    process.exit(1);
  }
  console.log('src/css.ts is up to date');
  process.exit(0);
}

writeFileSync(outPath, source);
console.log(`Wrote ${outPath}`);
